# Generated by Django 4.2.7 on 2023-12-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='用户名')),
                ('gid', models.CharField(max_length=20, verbose_name='房间号')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='用户名')),
                ('msg', models.CharField(max_length=1024, verbose_name='消息')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('gid', models.CharField(max_length=20, verbose_name='房间号')),
                ('session_key', models.CharField(max_length=40, verbose_name='sessionid')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=255, verbose_name='密码')),
                ('this_time', models.DateTimeField(verbose_name='本次登录时间')),
                ('last_time', models.DateTimeField(verbose_name='上次登录时间')),
            ],
        ),
    ]
