# Generated by Django 4.2.7 on 2023-12-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='websocket连接')),
                ('uid', models.CharField(max_length=20, verbose_name='用户名')),
                ('gid', models.CharField(max_length=20, verbose_name='房间号')),
            ],
        ),
    ]
